version: 0.4.0.{build}
shallow_clone: true
# Don't actually build. This is not a .net project
build: false
branches:
    only:
      - master
cache:
    - '%LOCALAPPDATA%\downloads'
clone_folder: c:\projects\mapguide-api-bindings
before_build:
    - echo APPVEYOR_PROJECT_NAME          %APPVEYOR_PROJECT_NAME%
    - echo APPVEYOR_PROJECT_SLUG          %APPVEYOR_PROJECT_SLUG%
    - echo APPVEYOR_BUILD_FOLDER          %APPVEYOR_BUILD_FOLDER%
    - echo APPVEYOR_BUILD_ID              %APPVEYOR_BUILD_ID%
    - echo APPVEYOR_BUILD_NUMBER          %APPVEYOR_BUILD_NUMBER%
    - echo APPVEYOR_BUILD_VERSION         %APPVEYOR_BUILD_VERSION%
    - echo APPVEYOR_REPO_NAME             %APPVEYOR_REPO_NAME%
    - echo APPVEYOR_REPO_BRANCH           %APPVEYOR_REPO_BRANCH%
    - echo APPVEYOR_REPO_TAG              %APPVEYOR_REPO_TAG%
    - echo APPVEYOR_REPO_TAG_NAME         %APPVEYOR_REPO_TAG_NAME%
    - echo APPVEYOR_REPO_COMMIT           %APPVEYOR_REPO_COMMIT%
    - echo APPVEYOR_REPO_COMMIT_TIMESTAMP %APPVEYOR_REPO_COMMIT_TIMESTAMP%

install:
    - if not exist "%LOCALAPPDATA%\downloads" mkdir "%LOCALAPPDATA%\downloads"
    - if not exist "%LOCALAPPDATA%\downloads\mapguide-3.1-buildpack.7z" appveyor DownloadFile "https://github.com/jumpinjackie/mapguide-api-bindings/releases/download/v0.3/mapguide-3.1-buildpack.7z" -FileName %LOCALAPPDATA%\downloads\mapguide-3.1-buildpack.7z
    - if not exist "%LOCALAPPDATA%\downloads\swigwin-3.0.12.zip" appveyor DownloadFile "https://prdownloads.sourceforge.net/swig/swigwin-3.0.12.zip" -FileName %LOCALAPPDATA%\downloads\swigwin-3.0.12.zip
    - if not exist "%LOCALAPPDATA%\downloads\php-7.1.18-Win32-VC14-x64.zip" curl -fsSL -o "%LOCALAPPDATA%\downloads\php-7.1.18-Win32-VC14-x64.zip" https://windows.php.net/downloads/releases/php-7.1.18-Win32-VC14-x64.zip
    - if not exist "%LOCALAPPDATA%\downloads\php-7.1.18-Win32-VC14-x86.zip" curl -fsSL -o "%LOCALAPPDATA%\downloads\php-7.1.18-Win32-VC14-x86.zip" https://windows.php.net/downloads/releases/php-7.1.18-Win32-VC14-x86.zip
    - if not exist "%LOCALAPPDATA%\downloads\php-7.1.18.tar.gz" curl -fsSL -o "%LOCALAPPDATA%\downloads\php-7.1.18.tar.gz" http://php.net/get/php-7.1.18.tar.gz/from/this/mirror
    - 7z x %LOCALAPPDATA%\downloads\php-7.1.18.tar.gz -oc:\temp
    - 7z x c:\temp\php-7.1.18.tar -aos -oc:\projects\mapguide-api-bindings\thirdparty\php7\src
    - 7z x %LOCALAPPDATA%\downloads\php-7.1.18-Win32-VC14-x64.zip -oc:\projects\mapguide-api-bindings\runtimes\php\Release64
    - 7z x %LOCALAPPDATA%\downloads\php-7.1.18-Win32-VC14-x86.zip -oc:\projects\mapguide-api-bindings\runtimes\php\Release
    - 7z x %LOCALAPPDATA%\downloads\mapguide-3.1-buildpack.7z -oc:\projects\mapguide-api-bindings\sdk\3.1
    - 7z x %LOCALAPPDATA%\downloads\swigwin-3.0.12.zip -oc:\
#    - dir c:\projects\mapguide-api-bindings\thirdparty\php7\src\php-7.1.18
#    - dir c:\projects\mapguide-api-bindings\runtimes\php\Release64
#    - dir c:\projects\mapguide-api-bindings\runtimes\php\Release
#    - dir c:\projects\mapguide-api-bindings\sdk\3.1

test_script:
    - build_tools.cmd
    - envsetupsdk.cmd 3 1 1 9389 c:\swigwin-3.0.12 %APPVEYOR_BUILD_NUMBER%
#    - cmake_build.cmd c:\projects\mg_bindings_build
    - build.cmd
    - make_archives.cmd

artifacts:
  - path: .\packages\*.nupkg
    name: NuGetPackage
  - path: .\packages\*.zip
    name: Bindings