version: 0.4.0.{build}
shallow_clone: true
# Don't actually build. This is not a .net project
build: false
branches:
    only:
      - master
clone_folder: c:\projects\mapguide-api-bindings
before_build:
    - echo APPVEYOR_PROJECT_NAME          %APPVEYOR_PROJECT_NAME%
    - echo APPVEYOR_PROJECT_SLUG          %APPVEYOR_PROJECT_SLUG%
    - echo APPVEYOR_BUILD_FOLDER          %APPVEYOR_BUILD_FOLDER%
    - echo APPVEYOR_BUILD_ID              %APPVEYOR_BUILD_ID%
    - echo APPVEYOR_BUILD_NUMBER          %APPVEYOR_BUILD_NUMBER%
    - echo APPVEYOR_BUILD_VERSION         %APPVEYOR_BUILD_VERSION%
    - echo APPVEYOR_REPO_NAME             %APPVEYOR_REPO_NAME%
    - echo APPVEYOR_REPO_BRANCH           %APPVEYOR_REPO_BRANCH%
    - echo APPVEYOR_REPO_TAG              %APPVEYOR_REPO_TAG%
    - echo APPVEYOR_REPO_TAG_NAME         %APPVEYOR_REPO_TAG_NAME%
    - echo APPVEYOR_REPO_COMMIT           %APPVEYOR_REPO_COMMIT%
    - echo APPVEYOR_REPO_COMMIT_TIMESTAMP %APPVEYOR_REPO_COMMIT_TIMESTAMP%

install:
    - appveyor DownloadFile "https://github.com/jumpinjackie/mapguide-api-bindings/releases/download/v0.3/mapguide-3.1-buildpack.7z"
    - appveyor DownloadFile "http://prdownloads.sourceforge.net/swig/swigwin-3.0.12.zip"
    - 7z x mapguide-3.1-buildpack.7z -oc:\projects\mapguide-api-bindings\sdk\3.1
    - 7z x swigwin-3.0.12.zip -oc:\

test_script:
    - envsetupsdk.cmd 3 1 1 9389
    - cmake_build.cmd c:\projects\mg_bindings_build c:\swigwin-3.0.12