SET MG_OEM_ACE_INCLUDE_DIR=%MG_SOURCE_ROOT%/Oem/ACE/ACE_wrappers
SET MG_OEM_XERCES_INCLUDE_DIR=%MG_SOURCE_ROOT%/Oem/dbxml/xerces-c-src/src
SET MG_HTTPHANDLER_INCLUDE_DIR=%MG_SOURCE_ROOT%/Web/src/Httphandler
SET MG_WEBAPP_INCLUDE_DIR=%MG_SOURCE_ROOT%/Web/src/WebApp
SET MG_WEBSUPPORT_INCLUDE_DIR=%MG_SOURCE_ROOT%/Web/src/WebSupport
SET MG_MDFMODEL_INCLUDE_DIR=%MG_SOURCE_ROOT%/Common/MdfModel
SET MG_FOUNDATION_INCLUDE_DIR=%MG_SOURCE_ROOT%/Common/Foundation
SET MG_GEOMETRY_INCLUDE_DIR=%MG_SOURCE_ROOT%/Common/Geometry
SET MG_PLATFORMBASE_INCLUDE_DIR=%MG_SOURCE_ROOT%/Common/PlatformBase
SET MG_MAPGUIDECOMMON_INCLUDE_DIR=%MG_SOURCE_ROOT%/Common/MapGuideCommon

SET MG_OEM_ACE_LIB_ROOT=%MG_SOURCE_ROOT%/Oem/ACE/ACE_wrappers
SET MG_OEM_XERCES_LIB_ROOT=%MG_SOURCE_ROOT%/Oem/dbxml/xerces-c-src/Build