SET IMAKE_TOOL_PATH=%MG_SOURCE_DIR%/BuildTools/WebTools/IMake/Win32/IMake.exe
SET MG_OEM_ACE_INCLUDE_DIR=%MG_SOURCE_DIR%/Oem/ACE/ACE_wrappers
SET MG_OEM_XERCES_INCLUDE_DIR=%MG_SOURCE_DIR%/Oem/dbxml/xerces-c-src/src
SET MG_HTTPHANDLER_INCLUDE_DIR=%MG_SOURCE_DIR%/Web/src/Httphandler
SET MG_WEBAPP_INCLUDE_DIR=%MG_SOURCE_DIR%/Web/src/WebApp
SET MG_WEBSUPPORT_INCLUDE_DIR=%MG_SOURCE_DIR%/Web/src/WebSupport
SET MG_MDFMODEL_INCLUDE_DIR=%MG_SOURCE_DIR%/Common/MdfModel
SET MG_FOUNDATION_INCLUDE_DIR=%MG_SOURCE_DIR%/Common/Foundation
SET MG_GEOMETRY_INCLUDE_DIR=%MG_SOURCE_DIR%/Common/Geometry
SET MG_PLATFORMBASE_INCLUDE_DIR=%MG_SOURCE_DIR%/Common/PlatformBase
SET MG_MAPGUIDECOMMON_INCLUDE_DIR=%MG_SOURCE_DIR%/Common/MapGuideCommon

SET MG_OEM_ACE_LIB_ROOT=%MG_SOURCE_DIR%/Oem/ACE/ACE_wrappers
SET MG_OEM_XERCES_LIB_ROOT=%MG_SOURCE_DIR%/Oem/dbxml/xerces-c-src/Build